spring:
  application:
    name: ecommence-app

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
      minimumIdle: 10
    name: ecomm
    url: 'jdbc:postgresql://127.0.0.1:5432/ecomm'
    username: postgres
    password: Password@1
#    jpa:
#      show-sql: true
#      properties:
#        hibernate:
#          dialect: org.hibernate.dialect.PostgreSQLDialect
#          ddl-auto: none # Hibernate ddl auto (create, create-drop, validate, update)

  # JPA configuration
  jpa:
    properties:
      hibernate:
#        generate_statistics: true
# this is needed for ordering inserts in case of relationships
#        order_inserts: true
        default_schema: ecomm
        cache:
          use_second_level_cache: false
        jdbc:
          batch_size: 30
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format_sql: true
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: false


  # Flyway configuration
  flyway:
    schemas: ${spring.datasource.name}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}


# Security configuration
# Keystore/keys generated using JDK have validity of three months.
# Before using this code make sure to generate a new keys
# update these values accordingly.
app:
  security:
    jwt:
      keystore-location: jwt-keystore.jks
      keystore-password: Password@1
      key-alias: jwt-sign-key
      private-key-passphrase: Password@1


logging:
  level:
    ROOT: INFO
    org:
      springframework:
        transaction: DEBUG
        orm:
          jpa: DEBUG
    com:
      zaxxer:
        hikari: TRACE
#          HikariConfig: DEBUG

